apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux-db
  namespace: miniflux-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux-db
  template:
    metadata:
      labels:
        app: miniflux-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: miniflux-db-data
              mountPath: /var/lib/postgresql/data
          envFrom:
          - configMapRef:
              name: miniflux-db-config
      volumes:
        - name: miniflux-db-data
          persistentVolumeClaim:
            claimName: miniflux-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux-app
  namespace: miniflux-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux-app
  template:
    metadata:
      labels:
        app: miniflux-app
    spec:
      containers:
        - name: miniflux-server
          image: miniflux/miniflux:latest
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: miniflux-app-config
