apiVersion: v1
kind: Service
metadata:
  name: miniflux-db
  namespace: miniflux-ns
spec:
  selector:
    app: miniflux-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-app
  namespace: miniflux-ns
spec:
  selector:
    app: miniflux-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080